const opportunitiesData = {
    'Government-Exams': [
        {
            id: 1,
            name: 'Railway Recruitment Board (RRB) Exam',
            organization: 'Indian Railways',
            deadline: 'June 30, 2024',
            eligibility: '12th Grade, Qualification: As per specific RRB notification',
            description: 'RRB exams are conducted for various positions in the Indian Railways.',
            applyLink: 'https://www.rrb.gov.in/',
        },
        {
            id: 2,
            name: 'Bank Probationary Officer (PO) Exam',
            organization: 'Reserve Bank of India (RBI) and Public Sector Banks',
            deadline: 'July 15, 2024',
            eligibility: 'Bachelor\'s degree in any discipline',
            description: 'Bank PO exams are held for the recruitment of Probationary Officers in banks across India.',
            applyLink: 'https://www.rbi.org.in/',
        },
        {
            id: 3,
            name: 'Staff Selection Commission (SSC) CGL Exam',
            organization: 'Staff Selection Commission (SSC)',
            deadline: 'August 31, 2024',
            eligibility: 'Bachelor\'s degree in any discipline',
            description: 'The SSC CGL exam is conducted for recruitment to various government posts.',
            applyLink: 'https://ssc.nic.in/',
        },
        {
            id: 4,
            name: 'Indian Administrative Service (IAS) Exam',
            organization: 'Union Public Service Commission (UPSC)',
            deadline: 'March 1, 2024',
            eligibility: 'Bachelor\'s degree, Age Limit: 21-32 years',
            description: 'The UPSC IAS exam is one of the most prestigious civil services exams in India.',
            applyLink: 'https://www.upsc.gov.in/',
        },
    ],    
    
    'Private-Sector-Jobs': [
        {
            id: 5,
            name: 'Software Engineer',
            organization: 'Tata Consultancy Services (TCS)',
            deadline: 'March 30, 2024',
            eligibility: 'Bachelor\'s degree in Computer Science, Experience: 2 years',
            description: 'Join TCS as a software engineer and work on cutting-edge projects.',
            applyLink: 'https://www.tcs.com/careers',
        },
        {
            id: 6,
            name: 'IT Consultant',
            organization: 'Infosys',
            deadline: 'April 15, 2024',
            eligibility: 'Master\'s degree, Experience: 3 years',
            description: 'Join Infosys as an IT consultant and be part of our innovative solutions.',
            applyLink: 'https://www.infosys.com/careers',
        },
        {
            id: 7,
            name: 'Business Analyst',
            organization: 'Accenture',
            deadline: 'March 25, 2024',
            eligibility: 'Bachelor\'s degree, Experience: 2 years',
            description: 'Accenture is hiring business analysts to drive business transformations.',
            applyLink: 'https://www.accenture.com/careers',
        },
        {
            id: 8,
            name: 'Software Developer',
            organization: 'Persistent Systems',
            deadline: 'April 10, 2024',
            eligibility: 'Bachelor\'s degree in Computer Science, Experience: 2 years',
            description: 'Join Persistent Systems as a software developer and contribute to technology solutions.',
            applyLink: 'https://www.persistent.com/careers',
        },
    ],
    
    'Entrance-Exams': [
        {
            id: 9,
            name: 'Joint Entrance Examination (JEE)',
            organization: 'National Testing Agency (NTA)',
            deadline: 'April 30, 2024',
            eligibility: '12th Grade, Subjects: Physics, Chemistry, Mathematics',
            description: 'JEE is an entrance exam for engineering programs in India.',
            applyLink: 'https://jeemain.nta.nic.in/',
        },
        {
            id: 10,
            name: 'Graduate Aptitude Test in Engineering (GATE)',
            organization: 'Indian Institute of Technology (IIT)',
            deadline: 'March 15, 2024',
            eligibility: 'Bachelor\'s degree in Engineering or Science',
            description: 'GATE is a national-level exam for postgraduate engineering programs and research.',
            applyLink: 'https://gate.iitb.ac.in/',
        },
        {
            id: 11,
            name: 'Common Admission Test (CAT)',
            organization: 'Indian Institutes of Management (IIM)',
            deadline: 'September 30, 2024',
            eligibility: 'Bachelor\'s degree in any discipline',
            description: 'CAT is an entrance exam for admission to management programs in India.',
            applyLink: 'https://iimcat.ac.in/',
        },
        {
            id: 12,
            name: 'National Eligibility cum Entrance Test (NEET)',
            organization: 'National Testing Agency (NTA)',
            deadline: 'May 15, 2024',
            eligibility: '12th Grade, Subjects: Physics, Chemistry, Biology',
            description: 'NEET is a national-level medical entrance exam for admission to undergraduate medical and dental courses in India.',
            applyLink: 'https://ntaneet.nic.in/',
        },        
    ],
    'Internships': [
        {
            id: 13,
            name: 'Summer Software Development Internship',
            organization: 'Tech Innovators Inc.',
            deadline: 'May 30, 2024',
            eligibility: 'Undergraduate students, Duration: 3 months',
            description: 'Join Tech Innovators Inc. for a summer software development internship and gain hands-on experience in building innovative software solutions.',
            applyLink: 'https://www.techinnovators.com/careers/software-development-internship',
        },
        {
            id: 14,
            name: 'Marketing Internship for Summer',
            organization: 'Acme Marketing Agency',
            deadline: 'June 15, 2024',
            eligibility: 'Undergraduate and graduate students, Duration: 2 months',
            description: 'Experience the world of marketing with Acme Marketing Agency’s summer internship program and learn the art of digital marketing.',
            applyLink: 'https://www.acmemarketingagency.com/careers/marketing-internship',
        },
        {
            id: 15,
            name: 'Summer Data Science Internship',
            organization: 'XYZ Tech Solutions',
            deadline: 'June 30, 2024',
            eligibility: 'Graduate students with a background in data science, Duration: 3 months',
            description: 'Get hands-on with data science at XYZ Tech Solutions during the summer. Apply for our data science internship program.',
            applyLink: 'https://www.xyztechsolutions.com/internships/data-science-internship',
        },
        {
            id: 16,
            name: 'Summer Finance Internship',
            organization: 'Finance Experts Ltd.',
            deadline: 'July 10, 2024',
            eligibility: 'Undergraduate and graduate students, Duration: 2 months',
            description: 'Finance Experts Ltd. offers a summer internship in finance. Discover the world of finance with us!',
            applyLink: 'https://www.financeexperts.com/careers/finance-internship',
        },
    ],
    
    'Scholarships': [
        {
            id: 17,
            name: 'National Scholarship for Higher Education',
            organization: 'Government of India',
            deadline: 'August 31, 2024',
            eligibility: 'Undergraduate students, Minimum GPA: 3.5',
            description: 'The National Scholarship for Higher Education is a government initiative to support deserving undergraduate students in their pursuit of higher education in India.',
            applyLink: 'https://www.mhrd.gov.in/national-scholarship',
        },
        {
            id: 18,
            name: 'UGC Merit Scholarship for Undergraduate Students',
            organization: 'University Grants Commission (UGC)',
            deadline: 'September 10, 2024',
            eligibility: 'Undergraduate students, Minimum GPA: 3.7',
            description: 'The UGC Merit Scholarship for Undergraduate Students is offered by the UGC to promote and reward academic excellence at the undergraduate level.',
            applyLink: 'https://www.ugc.ac.in/ugc_schemes/',
        },
        {
            id: 19,
            name: 'Minority Scholarship for Undergraduate Students',
            organization: 'Ministry of Minority Affairs',
            deadline: 'August 25, 2024',
            eligibility: 'Undergraduate students from minority communities, Minimum GPA: 3.5',
            description: 'The Minority Scholarship for Undergraduate Students aims to provide financial support to students from minority communities pursuing higher education.',
            applyLink: 'https://scholarships.gov.in/',
        },
        {
            id: 20,
            name: 'Dr. Ambedkar Scholarship for Underprivileged Students',
            organization: 'Social Justice and Empowerment Department',
            deadline: 'September 5, 2024',
            eligibility: 'Undergraduate students from economically disadvantaged backgrounds, Minimum GPA: 3.7',
            description: 'The Dr. Ambedkar Scholarship is intended to assist underprivileged students in their undergraduate studies and reduce financial barriers.',
            applyLink: 'https://www.scholarships.gov.in/',
        },
    ],    

};

export default opportunitiesData;